CREATE TABLE IF NOT EXISTS clicks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    link_id BIGINT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_agent TEXT,
    ip_address INET,

    CONSTRAINT fk_clicks_link
        FOREIGN KEY (link_id)
        REFERENCES links(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_clicks_link_id
ON clicks(link_id);
